### ISSUE TITLE
Android: Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by fredrik-hjarner** [robinpowered/react-native-vitals#14]
I follow the installation instructions.
Then I write:

```
import Vitals from "react-native-vitals";

Vitals.getMemory(memory => {
  console.log("memory:", memory, "");
});
```

and the app crashes with the error message: Malformed calls from JS: field sizes are different

"react-native": "^0.58.6",
"react-native-vitals": "^1.0.4",

**Comment by fredrik-hjarner** [comment]
Aha, one should do:

```
Vitals.getMemory().then(memory => {
  console.log("memory:", memory, "");
});
```

the documentation is wrong.

**Comment by srartese** [comment]
Please update the readme with this information.
